/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmRouteImport } from './routes/_llm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmSearchRouteImport } from './routes/_llm/search'
import { Route as LlmEvalRouteImport } from './routes/_llm/eval'
import { Route as LlmBattleRouteImport } from './routes/_llm/battle'
import { Route as LlmChatPokemonIdRouteImport } from './routes/_llm/chat.$pokemonId'

const LlmRoute = LlmRouteImport.update({
  id: '/_llm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmSearchRoute = LlmSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LlmRoute,
} as any)
const LlmEvalRoute = LlmEvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => LlmRoute,
} as any)
const LlmBattleRoute = LlmBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => LlmRoute,
} as any)
const LlmChatPokemonIdRoute = LlmChatPokemonIdRouteImport.update({
  id: '/chat/$pokemonId',
  path: '/chat/$pokemonId',
  getParentRoute: () => LlmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle': typeof LlmBattleRoute
  '/eval': typeof LlmEvalRoute
  '/search': typeof LlmSearchRoute
  '/chat/$pokemonId': typeof LlmChatPokemonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle': typeof LlmBattleRoute
  '/eval': typeof LlmEvalRoute
  '/search': typeof LlmSearchRoute
  '/chat/$pokemonId': typeof LlmChatPokemonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_llm': typeof LlmRouteWithChildren
  '/_llm/battle': typeof LlmBattleRoute
  '/_llm/eval': typeof LlmEvalRoute
  '/_llm/search': typeof LlmSearchRoute
  '/_llm/chat/$pokemonId': typeof LlmChatPokemonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/battle' | '/eval' | '/search' | '/chat/$pokemonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/battle' | '/eval' | '/search' | '/chat/$pokemonId'
  id:
    | '__root__'
    | '/'
    | '/_llm'
    | '/_llm/battle'
    | '/_llm/eval'
    | '/_llm/search'
    | '/_llm/chat/$pokemonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmRoute: typeof LlmRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_llm': {
      id: '/_llm'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_llm/search': {
      id: '/_llm/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LlmSearchRouteImport
      parentRoute: typeof LlmRoute
    }
    '/_llm/eval': {
      id: '/_llm/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof LlmEvalRouteImport
      parentRoute: typeof LlmRoute
    }
    '/_llm/battle': {
      id: '/_llm/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof LlmBattleRouteImport
      parentRoute: typeof LlmRoute
    }
    '/_llm/chat/$pokemonId': {
      id: '/_llm/chat/$pokemonId'
      path: '/chat/$pokemonId'
      fullPath: '/chat/$pokemonId'
      preLoaderRoute: typeof LlmChatPokemonIdRouteImport
      parentRoute: typeof LlmRoute
    }
  }
}

interface LlmRouteChildren {
  LlmBattleRoute: typeof LlmBattleRoute
  LlmEvalRoute: typeof LlmEvalRoute
  LlmSearchRoute: typeof LlmSearchRoute
  LlmChatPokemonIdRoute: typeof LlmChatPokemonIdRoute
}

const LlmRouteChildren: LlmRouteChildren = {
  LlmBattleRoute: LlmBattleRoute,
  LlmEvalRoute: LlmEvalRoute,
  LlmSearchRoute: LlmSearchRoute,
  LlmChatPokemonIdRoute: LlmChatPokemonIdRoute,
}

const LlmRouteWithChildren = LlmRoute._addFileChildren(LlmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmRoute: LlmRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
